feat(git):[TRI-281] Add commit-message git-hook
catenax/ItemRelationshipServices pull request #23
Opened 2022-03-31 14:53 UTC by ds-jhartmann

Added git-hook for commit messages

2022-03-31 15:24 UTC, mkanal requested changes
Hi Jaro, 
Review was finished. 
Thank you very much,

2022-03-31 15:24 UTC, mkanal commented on README.md
> +For further information please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format
What information should be get from an angular.js site. Probably we should refer another page which is desrcibing the semantic commit messages. Angular.js is more frontend and could irritate  the developer

2022-03-31 15:24 UTC, mkanal commented on dev/commit-msg
> +	echo "Missing argument (commit message). Did you try to run this manually?"
What does "Did you try to run this manually" mean in this context. Please give more context in the message.

2022-03-31 15:24 UTC, mkanal commented on dev/commit-msg
> +	echo "Please see https://github.com/catenax/ItemRelationshipServices#commit-messages"
is it possible to use a a var instead of a url. If we change the repository we have to change the url .

2022-03-31 15:24 UTC, mkanal commented on dev/commit-msg
> +	echo "Please see https://github.com/catenax/ItemRelationshipServices#commit-messages"
;-) Thank you very much.

2022-03-31 15:33 UTC, ds-jhartmann commented on dev/commit-msg
> +	echo "Missing argument (commit message). Did you try to run this manually?"
This message will be displayed when you don't provide any commit message or execute the script on your local machine without arguments like this: "./commit-msg".
This was already present in the example and I didn't see a reason to remove it.
IMO we don't need to specify this further.

2022-04-01 08:24 UTC, mkanal approved these changes

2022-04-01 08:24 UTC, merged