Feature/tri 290 swagger documentation irs
catenax/ItemRelationshipServices pull request #28
Opened 2022-04-05 14:30 UTC by mkanal

Thank you in advance.

2022-04-05 17:03 UTC, ds-jkreutzfeld requested changes
I fixed the checkstyle issues to have a clean build.
The API comparison test is now failing, please check whether this test is still relevant.

2022-04-06 06:09 UTC, mkanal commented on irs-api/src/main/java/net/catenax/irs/exceptions/IrsApiException.java
> +public class IrsApiException {
Will be removed. Is not used.

2022-04-06 06:10 UTC, mkanal commented on irs-api/src/main/java/net/catenax/irs/requests/IrsPartsTreeRequest.java
> +    @Size(min = 25, max = 25)
@Size(min = IrsApiConstants.JOB_ID_SIZE, max = IrsApiConstants.JOB_ID_SIZE)

2022-04-07 12:59 UTC, jzbmw approved these changes
Ive overlooked some topics. Im by far not qualified to check if these topics are valid or not

2022-04-07 17:04 UTC, merged