Feature/tri 337
catenax/ItemRelationshipServices pull request #35
Opened 2022-04-07 12:28 UTC by SaberIstos

https://jira.catena-x.net/browse/TRI-337

2022-04-08 10:05 UTC, ds-ext-kmassalski requested changes
@SaberIstos SubmodelClient was refactored on another branch, so this pull request need changes. Right now we are not using feign for submodel retrieval. Please merge main branch, and provide changes accordingly.

2022-04-11 10:54 UTC, ds-ext-kmassalski requested changes

2022-04-11 10:54 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/AssemblyPartRelationship.java
> +public class AssemblyPartRelationship {
Change visibility to package

2022-04-11 10:54 UTC, ds-ext-kmassalski commented on irs-api/pom.xml
> +        <dependency>
As we are using spring stack, on top of spring-boot - did you consider using spring-retry instead?
I think it would be more consistent:
https://www.baeldung.com/spring-retry

2022-04-11 12:21 UTC, ds-ext-kmassalski commented
Unit test is missing for service class :)

2022-04-11 16:56 UTC, SaberIstos commented on irs-api/pom.xml
> +        <dependency>
@ds-ext-kmassalski based on my research I found both solutions Spring Retry or Resilience4j Retry. I Chose the second one because it offers an equally easier configuration – either through code or through properties.

2022-04-12 10:40 UTC, ds-ext-kmassalski requested changes

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-parent/pom.xml
> +        <feign.version>11.8</feign.version>
Remove redundant property

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelRetryer.java
> +     * @return the object RetryConfig
1. You used @Getter annotation on the class level, which means that RetryRegistry can be accesed anyway - without this method
2. But why is this RetryConfig needed outside of this class anyway? Only for unit test purpose?

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClient.java
> +class SubmodelClientImplStub implements SubmodelClient {
It seems like you provided implementation of SubmodelClient only for unit test purpose, what is pretty bad.
If thats the case its a lot better to:

1. provide throw exception mock in tests (pseudo code below):
```
SubmodelClient submodelClient= mock(SubmodelClient.class);
    when(submodelClient.getSubmodel(anyString()))
      .thenThrow(HttpServerErrorException.class);
```
2. Alternative: move SubmodelClientImplStub to test resources as here its redundant

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-api/pom.xml
> +        <dependency>
So I think we need decision which dependency we want to use.   It's also possible to configure Spring retry with properties. In my opinion sprint retry fits better to our stack, @ds-jkreutzfeld what u think?

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-api/src/main/resources/application-local.yml
> +        url: http://stub
Please remove not needed properties

2022-04-12 10:40 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelRetryerTest.java
> +        if (this.retryConfig != null) {
You should provide two unit tests instead testing few things inside one test.
The idea with unit testing is to isolate one thing and prove whether or not it works.

2022-04-13 06:49 UTC, ds-jkreutzfeld commented on irs-api/pom.xml
> +        <dependency>
I agree that Spring Retry fits well to our stack, but Resilience4j seems to be the base for a lot of spring resilience tools as well, so we are not totally off.
Additional to the retry functionality, Resilience4j offers CircuitBreaker and Bulkhead functionality which we should consider in the future for our interfaces.

I think either lib is fine here, so my vote goes to the current implementation. 😀

2022-04-13 06:49 UTC, ds-jkreutzfeld commented on irs-api/pom.xml
> +        <dependency>
I agree that Spring Retry fits well to our stack, but Resilience4j seems to be the base for a lot of spring resilience tools as well, so we are not totally off.
Additional to the retry functionality, Resilience4j offers CircuitBreaker and Bulkhead functionality which we should consider in the future for our interfaces.

I think either lib is fine here, so my vote goes to the current implementation. 😀

2022-04-13 06:54 UTC, ds-jkreutzfeld approved these changes

2022-04-13 09:43 UTC, ds-ext-kmassalski commented
@SaberIstos as we agreed, please remove SubmodelRetryer service and use existing one's.

2022-04-13 12:24 UTC, ds-ext-kmassalski requested changes
Check last comments, provide correct test if method was "retried" few times

2022-04-13 12:24 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +
I was expecting to add @Retry on getSubmodel method that was already there, and not to add new public method.
So please annotation getSubmodel, or make retrySubmodel private and execute it inside getSubmodel method.

2022-04-13 12:24 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelRetryerTest.java
> +
You are not testing if the method was executed exactly three times - so you are not testing if retry mechanism worked.
The only validation you did here is that exception was thrown, nothing else.
Please provide proper test, Mockito.verify can be used to verify number of executions , eg.:
`org.mockito.Mockito.verify(mockObject, times(3)).someMethod("was called exactly three times");`

2022-04-13 13:37 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +
The goal of the task is to provide an approach of a retry mechanism for retrieving submodels. Since the SubmodelClientLocalStub seems to be created only for test propose, I provided my solution on the method retrySubmodel.
Sure the existing method public AssemblyPartRelationshipDTO getSubmodel can be annotated with @Retry but not with calling a private method inside it. So I guess we can keep it.

2022-04-13 14:17 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +
The thing is that getSubmodel is already being used by other 'service' class in further processing :) 
So by adding new  retrySubmodel method, you would also how to change business logic in other places of applcation. You should not do this - use getSubmodel instead, and provide retry here. In test you are mocking SubmodelClient anyway, so Im not sure what you mean by "SubmodelClientLocalStub is created for tests"

2022-04-15 06:51 UTC, ds-ext-kmassalski approved these changes

2022-04-15 06:51 UTC, merged